#!/usr/bin/env bash

cd /autograder/source

# Set up & run Python autograder files
cp -r /autograder/submission/python /autograder/source
python3 run_tests.py > results-python.json

# Set up & run R autograder files
cp -r /autograder/submission/R /autograder/source
Rscript run_tests.R > results-R.json

## Merges results from both runs.
python3 merge_scores.py > /autograder/results/results.json